#!/usr/bin/sh

sleep_pid=""
this_pid=$$

#### FUNCTIONS

# Disk
DRIVES=(@STATUSBAR_DRIVES@)
function statusbar_disk() {
  local driveno=${#DRIVES[@]}
  local drivein=$(($RANDOM % $driveno))
  local drive=${DRIVES[drivein]}

  df --output='size,used,target' -BKB "$drive" | awk -v drive=$drive '
    BEGIN {
      sufs[0]="M"; sufs[1]="G"; sufs[2]="T"; sufs[3]="E"
    }
    NR == 2 {
      total=$1
      used=$2
      target=$3

      gsub("kB","",total)
      gsub("kB","",used)

      total_suf=""; used_suf="";

      it=0
      while (it <= 3 && total >= 1000) {
         total=total / 1000
         total_suf=sufs[it]
         it++
      }

      it=0
      while (it <= 3 && used >= 1000) {
         used=used / 1000
         used_suf=sufs[it]
         it++
      }

      perc=(used / total) * 100

      # printf("%s %s %.2f%sB/%.2f%sB [%.2f%%]",
      #   drive, target, used, used_suf, total, total_suf, perc)
      printf("%s %.2f%sB/%.2f%sB [%.2f%%]",
        target, used, used_suf, total, total_suf, perc)
      exit
    }'
}

# Volume
function statusbar_vol() {
  local vol=$(amixer get Master |\
                grep -Eo '\[[0-9]{1,3}%\] \[-?[0-9]{1,3}\.[0-9]{1,2}dB')
  local db=${vol/\[*%\] /}
  local perc=${vol/$db/}
  perc=${perc/\[/}
  perc=${perc/\]/}
  echo "$perc$db]"
}

# Memory
function statusbar_mem() {
  awk -F: '
    /^MemTotal/ {
       total_kb=$2; total=$2/1000000
    }
    /^Active:/ {
      used_kb=$2; used_suf="M"; used=$2/1000;
      if (used > 1000) {used_suf="G"; used=used/1000}
      perc=((used_kb / total_kb) * 100)
    }
    END {
      printf("%.2f%sB/%.2fGB [%.2f%%]\n", used, used_suf, total, perc)
    }' /proc/meminfo
}

# Network
IF="eth0"
function statusbar_net() {
  local ip=$(awk '
    /^ {11}\|-- 192\.168\.[0-9]{1,3}\.[^0]/ {
      ifm=$0
      gsub("^ {11}\\|-- 192.168.", "", ifm)
      printf("*.%s", ifm)
      exit
    }' /proc/net/fib_trie)

  local ipstat=$(awk '
    BEGIN {
      sufs[0]="K"; sufs[1]="M"; sufs[2]="G"; sufs[3]="T"; sufs[4]="P"
    }

    /eth0/ {
      dnb_suf=""; upb_suf="";
      dnb=$2; upb=$10;

      it=0
      while (it <= 4 && dnb >= 1000) {
         dnb=dnb / 1000
         dnb_suf=sufs[it]
         it++
      }

      it=0
      while (it <= 4 && upb >= 1000) {
         upb=upb / 1000
         upb_suf=sufs[it]
         it++
      }

      printf("[%.2f%sB/%.2f%sB]", dnb, dnb_suf, upb, upb_suf); exit
    }' /proc/net/dev)

  echo "$ip $ipstat"
}

# Uptime
function statusbar_uptime() {
  awk '
    {
      minutes=int($1 / 60); hours=int(minutes / 60)
      if (hours < 10) { hours="0" hours}
      minutes_rem=minutes % 60
      if (minutes_rem < 10) { minutes_rem="0" minutes_rem}
      printf("%s%s up", hours, minutes_rem)
    }' /proc/uptime
}

# Kernel
function statusbar_kernel() {
  echo "Linux $(cut -d' ' -f3 /proc/version)"
}

# Time
function statusbar_date() {
  local date=$(date +'%Y%m%d-%w %I%M%p')
  echo "$date"
}

function statusbar_xlayout() {
  @STATUSBAR_XLAYOUT@
}

FUNCTIONS=('date' 'disk' 'kernel' 'mem' 'net' 'uptime' 'vol' 'xlayout')

#### Constructor

# mkbar FUNCS...
function mkbar() {
  local bar=" "
  local res=""

  for func in $@; do
    res=$(eval $func)

    bar+="$res | "
  done

  echo $echo_opt "${bar%|*}"
}

#### Main

case $1 in
  '--help'|'-h')
    echo "Usage: statusbar [OPT] FUNCTIONS..."
    echo "Description: Output a status given certain built-in functions"
    echo "Options:
  -i INTV: use INTV interval (run continously, updating either when INTV seconds
    pass, or USR1 signal is sent)
  -n: output newline at the end
  -s: handle USR1 as update (sleep indefinitely)"
    echo "Available functions:"
    for func in ${FUNCTIONS[@]}; do
      echo "  - ${func}"
    done
    exit 0;;
esac

FUNCS=""

INTV=""
req_intv=false
echo_opt="-n"

for arg in $@; do
  if $req_intv; then
    req_intv=false
    INTV=$arg
    continue
  fi

  case $arg in
    '-i') req_intv=true ;;
    '-n') echo_opt="" ;;
    '-s') INTV="infinity" ;;
    *) FUNCS+="statusbar_$arg "
  esac
done

if $req_intv; then
  echo "[ !! ] Missing interval"
  exit 1
fi

if [[ -z $FUNCS ]]; then
  echo "[ !! ] Missing functions. See \`--help'"
  exit 1
fi

if [[ ! -z $INTV ]]; then
  trap 'kill -9 $sleep_pid >& /dev/null' USR1
  trap 'kill -9 $sleep_pid $this_pid >& /dev/null' TERM

  echo "$this_pid" > /tmp/statusbar-pid

  while :; do
    mkbar $FUNCS

    sleep $INTV &
    sleep_pid=$!

    wait $sleep_pid
  done
else
  mkbar $FUNCS
fi
