#!/usr/bin/sh

case $1 in
	'-h'|'--help')
		echo "Usage:       copylog.sh"
		echo "Description: Temporary script for copying logs for the OpenRC spiel"
		exit 1
		;;
esac

DATE=$(date +%Y%m%d%H%M)

echo "[ .. ] Copying as per state found on the ${DATE}"

cp --preserve=all --verbose /openrc.log Log/openrc/openrc-${DATE}.log
