#!/usr/bin/bash

## Xsession counterpart for the TTY

# used for the emacs server to set itself up for a TTYsession
export WM="$1"
export TERM=linux

mkdir -pv /tmp/emacs
touch /tmp/emacs/daemon.log

mpd &

# this will fail if emacs has an existing session
case $WM in
  'tty'|'tmux-tty')
    SESSION=zsh

    emacss start >> /tmp/emacs/daemon.log 2>&1 && \
      docs -t journal >> /tmp/emacs/daemon.log 2>&1

    if [[ $XSESSION == "1" && ! -f /tmp/xsession.lock ]]; then
      # locked: ignore launching `linux.sh'
      touch /tmp/xsession.lock

      tmux -f "/home/p/config/tmux-tty.conf" new-session -d \
           -e XINITSLEEP='/home/mh/Scripts/system/linux.sh' \
           -s ttysession zsh
    fi ;;

  # we don't start the server when running `emacs-tty'
  'emacs-tty')
    export XSESSION="$2"
    SESSION=emacs

    if [[ $XSESSION == "1" ]]; then
      export XINITSLEEP='/home/mh/Scripts/system/linux.sh'
    else
      unset XINITSLEEP
    fi;;
esac

if [[ $WM == 'tty' ]]; then
  tmux -f "/home/p/config/tmux-tty.conf" attach-session -t 'docs'
fi

exec $SESSION
