#!/usr/bin/bash

# $1 is ignored for backwards-compatibility

SHELL=zsh

# used for the emacs server to set itself up for a TTYsession
export TTYSESSION=yes

mkdir -pv /tmp/emacs
touch /tmp/emacs/daemon.log

# this will fail if emacs has an existing session
emacss start >> /tmp/emacs/daemon.log 2>&1 &&  \
  sleep 1 && docs journal >> /tmp/emacs/daemon.log 2>&1

# no session: ignore the rest of the script
if [[ $2 == "1" ]]; then
  # locked: ignore launching `linux.sh'
  if [[ -f /tmp/ttysession.lock ]]; then
    exit 0
  else
    touch /tmp/ttysession.lock

    # BASH is only for a TTYsession script
    export TTYSESSIONSLEEP='/home/mh/Scripts/system/linux.sh'
    tmux new $SHELL
  fi
fi

exec $SHELL
