#!/usr/bin/bash

source @BASH_PROFILE_BASH_ENVIRONMENT@

# load schedl
@BASH_PROFILE_SCHEDL@

# load `session' if `system-day' is set by `schedl', 0 if doesn't exist, one if
# it does
exec session $([[ -f /tmp/schedl/system-day ]];
               if (( $? == 0 )) ; then echo 1 ; else echo 0 ; fi)
