# Prompt
TTY=$(tty)

red="\033[0;31m"
bold="\033[0;1m"
reset="\033[0m"

PS1="\
\[$red\]┌[\[$bold\]\u\[$red\]@\[$bold\]\H\[$red\]] \
[\[$bold\]${TTY}\[$red\]] [\[$bold\]bash\[$red\]]
\[$red\]└[\[$bold\]\w\[$red\]]>\[$reset\] "
PS2=" \[$red\]|> \[$reset\]"

# Common source
source /home/mh/Scripts/sh/alias
source /home/mh/Scripts/sh/environment
source /home/mh/Scripts/sh/functions
cat /home/mh/Documents/Ascii/linux.txt

export SHELL=/bin/bash
