#!/usr/bin/bash

function log {
  echo "$@" 1>&2
}

THIS=$0
THIS=${THIS##*/}

case $1 in
  '--help'|'-h')
    echo "Usage:       $THIS [OPTIONS...] [PROG]"
    echo "Description: Starts or kills some PROG program with dbus"
    echo "Options:
  -s, --start: start (default)
  -f, --file: use environment file
  -l, --list: lists dbus-like processes
  -S, --stop: kill program and the bus
  -k, --keep-bus: ignore the killing dbus"
    exit 1;;
esac

self="$$"
SHELL=/usr/bin/zsh

no_prog=false
keep_bus=false

on_file=false
on_sys=false

op=start
prog=""

for arg in $@; do
  case $arg in
    '-s'|'--start')
      op=start;;
    '-S'|'--stop')
      op=stop;;
    '-l'|'--list')
      no_prog=true
      op=list;;
    '-f'|'--file')
      on_file=true;;
    '-k'|'--keep-bus')
      keep_bus=true;;
    *)
      prog+="$arg "
  esac
done

case $op in
  'list')
    log "[ == ] pgrep -af dbus"
    pgrep -af dbus | grep -v "^$self" ;;

  'start')
    if [[ -z $prog && $no_prog == 'false' ]]; then
      log "[ WW ] No program was specified. Defaulting to SHELL"
      prog="$SHELL"
    fi

    log "[ == ] dbus-launch $prog"

    if $on_file; then
      log "[ == ] Using file"

      if [[ ! -f /tmp/dbus-env ]]; then
        export DBUS_SESSION_BUS_ADDRESS=$(dbus-launch sh -c "echo \$DBUS_SESSION_BUS_ADDRESS")
        echo "export DBUS_SESSION_BUS_ADDRESS=\"$DBUS_SESSION_BUS_ADDRESS\"" > /tmp/dbus-env
      else
        eval $(cat /tmp/dbus-env)
      fi

      exec $prog
    else
      exec dbus-launch $prog
    fi ;;

  'stop')
    if $on_file; then
      rm -v /tmp/dbus-env
    fi

    if [[ -z $prog ]]; then
      no_prog=true
    fi

    if ! $no_prog; then
      log "[ == ] pkill -f -TERM $prog"
      eval pkill -f -TERM $prog
      log "[ == ] sleep 5"
      sleep 5
    fi

    if ! $keep_bus; then
      log "[ == ] pkill -f -TERM 'dbus-daemon.*--session$'"
      eval pkill -f -TERM 'dbus-daemon.*--session$'
    fi ;;
esac
