#!/usr/bin/bash

case $1 in
  '--help'|'-h')
    echo "Usage:       dbus-prog [OPTIONS...] [PROG]"
    echo "Description: Starts or kills some PROG program with dbus"
    echo "Options:
  --start: start (default)
  --file: use environment file
  --list: lists dbus-like processes
  --stop: kill program and the bus
  --keep-bus: ignore the killing dbus"
    exit 1;;
esac

self="$$"
SHELL=/usr/bin/zsh

no_prog=false
keep_bus=false

on_file=false
on_sys=false

op=start
prog=""

for arg in $@; do
  case $arg in
    '--start')
      op=start;;
    '--stop')
      op=stop;;
    '--list')
      no_prog=true
      op=list;;
    '--file')
      on_file=true;;
    '--keep-bus')
      keep_bus=true;;
    *)
      prog+="$arg "
  esac
done

if [[ -z $prog && $no_prog == 'false' ]]; then
  echo "[ WW ] No program was specified. Defaulting to SHELL"
  prog="$SHELL"
fi

case $op in
  'list')
    echo "[ == ] pgrep -af dbus"
    pgrep -af dbus | grep -v "^$self" ;;

  'start')
    echo "[ == ] dbus-launch $prog"

    if $on_file; then
      echo "[ == ] Using file"

      if [[ ! -f /tmp/dbus-env ]]; then
        export DBUS_SESSION_BUS_ADDRESS=$(dbus-launch sh -c "echo \$DBUS_SESSION_BUS_ADDRESS")
        echo "export DBUS_SESSION_BUS_ADDRESS=\"$DBUS_SESSION_BUS_ADDRESS\"" > /tmp/dbus-env
      else
        eval $(cat /tmp/dbus-env)
      fi

      exec $prog
    else
      exec dbus-launch $prog
    fi ;;

  'stop')
    if $on_file; then
      rm -v /tmp/dbus-env
    fi

    if ! $no_prog; then
      echo "[ == ] pkill -f -TERM $prog"
      eval pkill -f -TERM $prog
      echo "[ == ] sleep 5"
      sleep 5
    fi

    if ! $keep_bus; then
      echo "[ == ] pkill -f -TERM 'dbus-daemon.*--session$'"
      eval pkill -f -TERM 'dbus-daemon.*--session$'
    fi ;;
esac
