#!/usr/bin/sh

case $1 in
  '--help'|'-h')
    echo "Usage:       killpid PIDFILE [KILL OPTIONS]"
    echo "Description: Kills the process with PID defined in PIDFILE"
    exit 0;;
esac

PIDFILE=$1
KILL_OPTIONS=${@:2}

if [[ ! -f $PIDFILE ]]; then
  echo "[ !! ] No such file \`$PIDFILE'"
  exit 1
fi

[[ -z $KILL_OPTIONS ]] && KILL_OPTIONS="-s TERM"

PID=$(cat $PIDFILE)

echo "[ == ] kill $KILL_OPTIONS $PID"
eval kill $KILL_OPTIONS $PID

# FIXME: requires procfs. use linux goddammit
if [[ ! -d /proc/$PID ]]; then
  echo "[ .. ] Done: killed process, removing PIDFILE"
  rm $PIDFILE 2>/dev/null
  exit 0
else
  echo "[ !! ] Error: process was not killed. Maybe try adding \`-s KILL'?"
  exit 1
fi
