#!/usr/bin/bash

MIXER=amixer

case $1 in
  '-h'|'--help')
    echo "Usage:       headset [on|off]"
    echo "Description: Toggles between [on] or [off] states for auto-muting. \
No options outputs the current audio state"
    exit 1;;
esac

COMMAND=$1

case $COMMAND in
  'on')
    echo "[ .. ] Enabling headset"
    echo "[ == ] $MIXER sset \"Auto-Mute Mode\" Enabled"
    $MIXER sset "Auto-Mute Mode" Enabled
    sleep 0.5
    echo "[ == ] $MIXER set Headphone unmute"
    $MIXER set Headphone unmute
    echo "[ == ] $MIXER set Front mute"
    $MIXER set Front mute
    exit $?;;
  'off')
    echo "[ .. ] Disabling headset"
    echo "[ == ] $MIXER sset \"Auto-Mute Mode\" Disabled"
    $MIXER sset "Auto-Mute Mode" Disabled
    sleep 0.5
    echo "[ == ] $MIXER set Headphone mute"
    $MIXER set Headphone mute
    echo "[ == ] $MIXER set Front unmute"
    $MIXER set Front unmute
    exit $?;;
  *)
    echo "Headphone(s) active: "
    $MIXER get Headphone | sed -n \
                               -e '6s/.*\[\(on\|off\)\].*/  left: \1/p' \
                               -e '7s/.*\[\(on\|off\)\].*/  right: \1/p'
    echo "Headphone Auto-Mute: "
    $MIXER sget 'Auto-Mute Mode' | awk -F"'" "
/Item0/ {
  printf(\"  state: %s\n\", \$2);
}"
    exit 1;;
esac
