#!/usr/bin/sh

SHELL="zsh"

case $1 in
  '--help'|'-h')
    echo "\
Usage:       noeq CMDLINE"
    echo "\
Description: Execute CMDLINE without alsa's equalizer. A lot of programs don't
             like it"
    exit 0;;
  '')
     echo "W: Missing CMDLINE. Defaulting to shell." ;;
esac

args="${@}"

if [[ -z $args ]]; then
  args="$SHELL"
fi

exec env ALSA_PCM='plug:generic_boost' $args
