#!/usr/bin/bash

# $1: ACPI action

SUDO=doas
ACTION=$1

# so that `doas' can execute this without prompt for a password
SUSPEND="$(realpath @ACPI_CONFIRM_SUSPEND@)"

case $ACTION in
  'shutdown') COMMAND="poweroff now";;
  'reboot') COMMAND="reboot now";;
  'suspend') COMMAND="$SUSPEND mem";;
  'hibernate') COMMAND="$SUSPEND disk";;
  *) echo '[ !! ] Invalid command!'; exit 1 ;;
esac

read -p "[ ?? ] ${ACTION}? [Y/n] " ans

if [[ -z $ans || $ans == 'y' ]]; then
  echo "ACPI event sent:" "waiting to send ACPI event; press C-c to ignore it"
  sleep 3

  exec $SUDO $COMMAND
else
  echo "[ !! ] Cancelled"
  exit 1
fi
