#!/usr/bin/bash

# -x: use x (with tmux)
# -t: use tmux (attach)
# -f: force: don't run lock

AS=${0##*/}
AS_SESSION=${AS/do/}

use_x=false
use_tmux=false
force=false

SWITCH=''

for arg in $@; do
  case $arg in
    '-x') use_x=true; use_tmux=true ; SWITCH='-t' ;;
    '-t') use_tmux=true; SWITCH='-t' ;;
    '-f') force=true ;;
  esac
done

unset LOGINCMD

if $force; then
  LOGINCMD="@DOSHUTDOWN_LOGINCMD_CONFIRM@ $SWITCH"
else
  LOGINCMD="@DOSHUTDOWN_LOGINCMD_LOCK@ $SWITCH"
fi

if $use_tmux; then
  tmux new-session -d -s "$AS_SESSION" "LOGINCMD=\"$LOGINCMD\" zsh"

  if [[ $? == 1 ]]; then
    tmux kill-session -t "$AS_SESSION"

    tmux new-session -d -s "$AS_SESSION" "LOGINCMD=\"$LOGINCMD\" zsh"
  fi

  tmuxa $($use_x && echo '-x') "$AS_SESSION"
else
  exec $LOGINCMD
fi
