#!/usr/bin/bash

# -x: use x (with tmux)
# -t: use tmux (attach)

AS=${0##*/}
AS_SESSION=${AS/do/}

use_x=false
use_tmux=false

SWITCH=''

for arg in $@; do
  case $arg in
    '-x') use_x=true; use_tmux=true ; SWITCH='-t' ;;
    '-t') use_tmux=true; SWITCH='-t' ;;
  esac
done

unset LOGINCMD

LOGINCMD=@DOSUSPEND_CONFIRM@

if $use_tmux; then
  tmux new-session -d -s "$AS_SESSION" "LOGINCMD=$LOGINCMD zsh"

  if [[ $? == 1 ]]; then
    tmux kill-session -t "$AS_SESSION"

    tmux new-session -d -s "$AS_SESSION" "LOGINCMD=$LOGINCMD zsh"
  fi

  tmuxa $($use_x && echo '-x') "$AS_SESSION"
else
  exec $LOGINCMD
fi
