#!/usr/bin/bash

AS=${0##*/}
AS=${AS/-confirm/}
SUDO=doas

case $AS in
  'shutdown') COMMAND="poweroff now";;
  'reboot') COMMAND="reboot now";;
  *) echo '[ !! ] Invalid command!'; exit 1 ;;
esac

read -p "[ ?? ] ${AS}? [Y/n] " ans

if [[ -z $ans || $ans == 'y' ]]; then
  echo "ACPI event sent:" "waiting to send ACPI event; press C-c to ignore it"
  sleep 3

  exec $SUDO $COMMAND
else
  echo "[ !! ] Cancelled"
  exit 1
fi
