#!/usr/bin/bash

SUDO=doas
XTERM=urxvt

AS=${0##*/}
AS=${AS/-lock/}
ARG=

DOCS_SWITCH=""

# clear them first
unset XINITSLEEP
unset XINITSLEEPARGS

case $WM in
  'tmux-tty'|'tty')
     DOCS_SWITCH="-t" ;;
esac

# called by sxhkd; only call for non-emacs
if [[ -z $XSESSION ]]; then
  echo "[ .. ] Prompting user for checkout on the journal"
  sleep 3

  docs $DOCS_SWITCH journal
fi

# set locks
if [[ -d /tmp/pacman ]]; then
  if [[ -f /tmp/pacman/pacman-lock ]]; then
    echo "[ .. ] Package lock found:" "found package lock set by \`linux.sh'. Wait to shutdown"
    sleep 1
    ARG=p
  fi

  if [[ -f /tmp/pacman/paru-lock ]]; then
    echo "[ .. ] Package lock found (subsystem):" "also found lock for \`paru'"
    sleep 1
    ARG="${ARG}n"
  fi

  if [[ -f /tmp/pacman/efistub-lock ]]; then
    echo "[ .. ] Efistub lock found:" "found efistub lock set by \`linux.sh'. Wait to shutdown"
    sleep 1
    ARG="${ARG}e"
  fi
fi

echo "[ .. ] Preparing to send ACPI event..."

notify="printf '\a' > /dev/tty1"

for arg in $@; do
  if [[ $arg == '-x' ]]; then
    notify="printf '\a' > /dev/tty${DISPLAY:1:1}"
  fi
done

eval $notify

sleep 1

@SHUTDOWN_LOCK_LOCK@ "${ARG}:${AS}"
