#!/bin/sh

AS=${0##*/}
AS=${AS/-confirm/}

COMMAND=/home/p/scripts/acpi/${AS}.sh

read -p "[y/N] ${AS}? " ans

if [[ $ans = 'y' ]]; then
  doas $COMMAND
  exit $?
else
  echo "[ !! ] Cancelled"
  exit 1
fi
