#!/bin/sh

AS=${0##*/}
AS=${AS/-confirm/}

COMMAND=$(realpath @SUSPEND_CONFIRM_ACPI@)

read -p "[Y/n] ${AS}? " ans

if [[ -z $ans || $ans == 'y' ]]; then
  echo "ACPI event sent:" "waiting to send ACPI event; press C-c to ignore it"
  sleep 3

  doas $COMMAND
  exit $?
else
  echo "[ !! ] Cancelled"
  exit 1
fi
