#!/usr/bin/env bash

DMENU=@JAPANESE_DMENU_BIN@
EDITCLIP=@JAPANESE_DMENU_EDIT_COPY@
CLIPFILE="/tmp/clipboard"

PROMPT="\
roma -> kana
roma -> kanji
kanji -> kana
kanji -> roma
kana -> kanji
"

function feed {
	echo -ne "$1" | $DMENU -p "$2"
}

MODE=$(feed "$PROMPT" "mode")

[[ -z $MODE ]] && exit 1

WORD=$(feed "" "write")

[[ -z $WORD ]] && exit 1

case $MODE in
  "roma -> kana")
    romaji "$WORD" | tr -d '\000' | sed -f @JAPANESE_DMENU_ROMAJI_NORMSED@ > $CLIPFILE;;
  "roma -> kanji")
    romaji "$WORD" | tr -d '\000' | sed -f @JAPANESE_DMENU_ROMAJI_NORMSED@ -e 's:$: 1:' | kkc | kkc.awk > $CLIPFILE;;
  "kanji -> kana")
	  echo "$WORD" |\
		  KANWADICTPATH=@JAPANESE_DMENU_KAKASI_KANWADICT@\
		    ITAIJIDICTPATH=@JAPANESE_DMENU_KAKASI_ITAIJIDICT@\
		    kakasi -i utf8 -JH -KH > $CLIPFILE;;
  "kanji -> roma")
	  echo "$WORD" |\
		  KANWADICTPATH=@JAPANESE_DMENU_KAKASI_KANWADICT@\
		    ITAIJIDICTPATH=@JAPANESE_DMENU_KAKASI_ITAIJIDICT@\
		    kakasi -i utf8 -Ja -Ha -Ka > $CLIPFILE;;
  "kana -> kanji")
    echo "$WORD" |\
      sed 's:$: 1:' | kkc | kkc.awk > $CLIPFILE;;
esac

$EDITCLIP -i
