#!/usr/bin/env bash
# Made by mH (https://github.com/matthmr)

MAIM="maim --quiet -o -B -d 0.25 -u"
NOTIFY=herbec

OPT="\
window root
select
"

feeddmenu() {
	echo -ne "$1" | dmenu -p "$2"
}

main() {

	FILENAME=`feeddmenu "" "filename"`

	if [[ -z $FILENAME || $FILENAME = '\n' ]]
	then
		FILENAME=$(date +"%Y%m%d%k%M")
	fi

	OPT=`feeddmenu "$OPT" "option"`

	[[ -z $OPT ]] && exit 1

	$MAIM --$OPT > @MAIM_DMENU_DIR@
	$NOTIFY 'Screenshot taken' "Save as @MAIM_DMENU_DIR@/$FILENAME.png"
}

main
