#!/usr/bin/sh

case $1 in
  '--help'|'-h')
    echo "Usage:       61kbd esc/til"
    echo "Description: Changes the behaviour of the esc/til (top-left) key in \
61% keyboards"
    exit 0 ;;
  'esc')
    esc_kc=9
    til_kc=49 ;;
  'til')
    til_kc=9
    esc_kc=49 ;;
  *) echo "[ !! ] Unknown option. See \`--help'"
     exit 1 ;;
esac

xmodmap -verbose -e "keycode $esc_kc = Escape Escape Escape Escape"
xmodmap -verbose -e "keycode $til_kc = grave asciitilde grave asciitilde"
