#!/usr/bin/bash

function help {
  echo "Usage:       emacsserver [start|stop|status|restart|toggle|purge]"
  echo "Description: Starts an emacs server."
}

case $1 in
  '-h'|'--help')
    help
    exit 1;;
esac

if [[ -z $XDG_RUNTIME_DIR ]]; then
  BASE="/tmp/emacs-$UID"
else
  BASE="$XDG_RUNTIME_DIR/emacs"
fi

NOTIFY=herbe
SHELL=/usr/bin/sh
EMACS=/usr/bin/emacs
EMACSCLIENT=/usr/bin/emacsclient
EMACSCLIENT_OPTS="-s $BASE/server"

function emacseval {
  local lisp_expr=$1
  ${EMACSCLIENT} ${EMACSCLIENT_OPTS} -e "${lisp_expr}"
}

function start {
  if [[ -d $BASE && -S $BASE/server ]]; then
    $NOTIFY "start" "[ !! ] An emacs server is already running"
    if [[ -f $BASE/emacs.pid ]]; then
      exit 1
    else
      $NOTIFY "start" "[ WW ] Found a server running without a PID file; creating one"
      emacseval "(emacs-pid)" > $BASE/emacs.pid
      exit 1
    fi
  fi

  ${EMACS} --daemon & </dev/null &>/dev/null
  pid=$!

  sleep ${TIMEOUT:-5}

  local emacs_daemon_pid=$(emacseval "(emacs-pid)")
  echo ${emacs_daemon_pid} > $BASE/emacs.pid
  
  $NOTIFY "start" "started and emacs server"
}

function stop {
  local pid;

  if [[ ! -d $BASE ]]; then
    $NOTIFY "stop" "[ !! ] No emacs server was found"
    exit 1
  elif [[ -d $BASE && ! -S $BASE/server ]]; then
    $NOTIFY "stop" "[ !! ] No emacs server was found"
    exit 1
  fi

  if [[ ! -f $BASE/emacs.pid ]]; then
    pid=$(emacseval "(emacs-pid)")
  else
    pid=$(cat $BASE/emacs.pid)
  fi

  local emacs_lisp_expr="(kill-emacs)"

  emacseval "$emacs_lisp_expr" </dev/null &>/dev/null &

  echo "[ == ] Got daemon pid of \`$pid'"
  rm -v $BASE/emacs.pid
  #kill ${pid} 2>/dev/null
  
  $NOTIFY "stop" "stopped the emacs server"
}

function toggle {
  if [[ -d $BASE ]]; then
    if [[ -f $BASE/emacs.pid ]]; then
      stop
    else
      start
    fi
  else
    start
  fi
}

function xtoggle {
  if [[ -d $BASE ]]; then
    if [[ -f $BASE/emacs.pid ]]; then
      stop
    fi
  else
    start
  fi
}

function restart {
  local timeout=5s

  stop && \
    sleep $timeout && \
    start
}

function status {
  if [[ -d $BASE && -S $BASE/server ]]; then
    if [[ -f $BASE/emacs.pid ]]; then
      local emacs_pid=$(cat $BASE/emacs.pid)
      $NOTIFY "status" "[ OK ] Found an emacs server running with pid of ${emacs_pid}"
      exit 0
    else
      emacseval "(emacs-pid)" > $BASE/emacs.pid
      local emacs_pid=$(cat $BASE/emacs.pid)
    fi
  else
    $NOTIFY "status" "[ !! ] No emacs server was found"
    exit 1
  fi
}

function purge {
  local emacs_pid=$(emacseval "(emacs-pid)")
  kill -TERM $emacs_pid

  rm -rf $BASE/emacs.pid
  rm -rf $BASE/server
  $NOTIFY "purge" "[ OK ] Purged emacs server"
}

case $1 in
  'start')   start   || exit $?;;
  'stop')    stop    || exit $?;;
  'status')  status  || exit $?;;
  'restart') restart || exit $?;;
  'toggle')  toggle  || exit $?;;
  'purge')   purge   || exit $?;;
  'xtoggle') xtoggle || exit $?;;
  *)         help;      exit 1;;
esac

exit 0
