#!/usr/bin/sh
# MPC_FORMAT='[%title%|%file%][ - %artist%[ "%album%"][ (%date%)]]'
MPC_FORMAT='[%title%|%file%]'
THIS="$$"

case $1 in
  '--help'|'-h')
    echo "Usage:       herbe-mpc [COMMAND] [OPTIONS...] EVENT..."
    echo "Description: Enters a loop calling herbe everytime EVENT is sent by \
MPD"
    echo "Commands:
  - kill: kill any other herbe-mpc instance running
  - stop: suspend any other herbe-mpc instance running
  - cont: continue any other herbe-mpc instance running"
    exit 0 ;;
  'kill')
    pkill -f '^mpc idle$'
    exit 0 ;;
  'stop')
    pkill -STOP -f '^mpc idle$'
    exit 0 ;;
  'cont')
    pkill -CONT -f '^mpc idle$'
    exit 0 ;;
  *) EVENTS="$(echo $@ | tr ' ' '|')" ;;
esac

if [[ -z "$EVENTS" ]]; then
  echo "[ !! ] Missing EVENT. See \`--help'"
  exit 1
fi

if pgrep -f '/herbe-mpc ' | grep -qv "$THIS"; then
  echo "[ !! ] Another herbe-mpc is already running"
  exit 1
fi

while :; do
  event=$(mpc idle)

  # kill program if `mpc idle' sent nothing. only true if it was killed
  if [[ -z $event ]]; then
    break
  fi

  if [[ $event =~ $EVENTS ]]; then
    herbec "$(mpc)" &
  fi
done

exit 0
