#!/usr/bin/sh

file=/tmp/.wp.png

if [[ ! -f $file ]]; then
  if [[ -s /tmp/.wp ]]; then
    source=$(cat /tmp/.wp)
  else
    source=~/.wp
  fi

  if [[ ! $(file --dereference --mime $source) =~ '/png' ]]; then
    ffmpeg -y -v 0 -vf 'scale=1920x1080' -i "$source" $file
  else
    file=$source
  fi
fi

i3lock -i "$file" -e -f -b -n -t -p default
