#!/usr/bin/sh

XMOUSE=mouse
PROP='Device Accel Constant Deceleration'

# changing acceleration was only needed when the left side of the desk was small
# for a mousepad
# FAST_ACC='0.6'
# LOW_ACC='1'

speed=''

p_var=''

case $1 in
  '--help'|'-h')
    echo "Usage:       mouse [on|on|left|right|speed] [value]"
    echo "Description: Enables/Disables the X mouse \`$XMOUSE'"
    exit 0 ;;
  'on')
     xinput $1 $XMOUSE ;;
  'off')
     xinput $1 $XMOUSE ;;
  'left')
    xmodmap -e 'pointer = 1 2 3' ;;
    # xinput set-prop $XMOUSE "$PROP" $FAST_ACC ;;
  'right')
    xmodmap -e 'pointer = 3 2 1' ;;
    # xinput set-prop $MOUSE "$PROP" $LOW_ACC ;;
  'speed')
    p_var='speed' ;;
  *) echo "[ !! ] Unknown option. See \`--help'"
     exit 1 ;;
esac

if [[ ! -z $p_var ]]; then
  eval $p_var="$2"
fi

if [[ ! -z $speed ]]; then
  xinput set-prop $XMOUSE 269 $speed
fi
