#!/usr/bin/env bash
#UPDATE(20221122): no longer using `~p/scripts/date/long.sh'

AS=${0##*/}

DMENU=@SCREENSHOT_DMENU_BIN@
SCREENSHOT=@SCREENSHOT_SHOTGUN_BIN@
SCREENSHOT_OPTS=""
SCREENSHOT_DIR=@SCREENSHOT_SHOTGUN_DIR@
SCREENSHOT_TMP_DIR=@SCREENSHOT_TMP_DIR@
NOTIFY=herbe

OPT_X11_GEOM=@SCREENSHOT_X11_GEOM@

OPT="\
window root
select
"

function feeddmenu {
	echo -ne "$1" | $DMENU -p "$2"
}

function feedopt {
  [[ -z $1 ]] && exit 1

  case $1 in
    'window root')
      echo '-s';;
    'select')
      echo "-g $($OPT_X11_GEOM)";;
    *)
      exit 1;;
  esac
}

case $AS in
  'screenshot-quick')
    FILENAME=/tmp/$(date +"%Y%m%d%H%M%S").png
    SCREENSHOT_OPTS='-s';;
  'screenshot-quick-dir')
    FILENAME=$SCREENSHOT_TMP_DIR/$(date +"%Y%m%d%H%M%S").png
    SCREENSHOT_OPTS='-s';;
  *)
    FILENAME=`feeddmenu "" "filename"`
    if [[ -z $FILENAME ]]; then
      exit 1
    else
      OPT=`feeddmenu "$OPT" "option"`
      SCREENSHOT_OPTS=$(feedopt "$OPT")
    fi
    FILENAME=$FILENAME.png;;
esac

if [[ $AS = 'screenshot-dir' ]]; then
  FILENAME=$SCREENSHOT_DIR/$FILENAME
fi

$SCREENSHOT $SCREENSHOT_OPTS $FILENAME
$NOTIFY 'Screenshot taken' "Save as $FILENAME"
