#!/usr/bin/sh

case $1 in
  '--help'|'-h')
    echo "Usage:       urxvt-tint COLOR"
    echo "Description: Color URXVT with tint COLOR from 00 to FF"
    exit 0;;
  *)
    TINT=$1;;
esac

TINT=$(printf "%3s" | sed -n "s/ /$TINT/gp")

printf "]705;#${TINT}"
