#!/usr/bin/sh

# start X daemons/scripts
# By session:
#   $1: wm

# Load Xresources
xrdb @XDAEMON_XRESOURCES@

if [[ -z `pidof sxhkd` ]]; then
  sxhkd -a 'bracketleft' < /dev/null >& /dev/null &
fi

# `xkbset ma` syntax:
#    [mk-delay> <mk_interval> <mk_time_to_max mk-max_speed> <mk_curve]
xkbset ma 30 10 25 15 2 &

# clipmenu
clipmenud &

# > nice pape anon
wpset -d @XDAEMON_WPDIR@ &

# start bar (not for i3)
if [[ $1 != i3 ]]; then
  polybar-start mh-$1 &
fi

# I don't think can do this in XKB source
#         BS UP LFT RGH DWN
for kc in 51 98 100 102 104; do xset r $kc; done

# start session
@XDAEMON_SESSION_INIT@ x "$1" &
