#!/usr/bin/sh

# start X daemons

# [ -z `pidof dunst` ] && dunst &

if [[ -z `pidof sxhkd` ]]; then
  sxhkd < /dev/null >& /dev/null &
fi

# Unused
#xmodmap /home/mh/.Xmodmap &
#xcape -e 'Control_L=Escape' &

# Mice are for pussies
# `xkbset ma` syntax:
#    [mk-delay> <mk_interval> <mk_time_to_max mk-max_speed> <mk_curve]
xkbset ma 30 10 25 15 2 &

# No fucking bell
# xset b off &

# Load Xresources
xrdb /home/mh/.Xresources &

# Nice wp anon
nitrogen --restore &
