#!/usr/bin/bash

WM=$1
TERM=st
TIMEOUT=5

# wait for X to start, if it hasn't yet, keep waiting...
sleep $TIMEOUT
while :
do
  pidof $WM > /dev/null && break || sleep $TIMEOUT
done

# start WM-specific programs
case $WM in
  # See (20221106)
  #/tmp/dbus-launch /mnt/ssd/root/usr/bin/dunst < /dev/null >& /dev/null &
  # xsetroot -xcf /home/mh/.icons/McMojave-cursors/cursors/default 32 &;;
  'dwm'|'dwm-git')
    mkdir -pv /tmp/emacs
    touch /tmp/emacs/daemon.log
    emacss start >> /tmp/emacs/daemon.log 2>&1 &&  \
      sleep 1 && docs -x journal > /dev/null 2>&1 &;;
esac

# no session: ignore the rest of the script
if [[ $2 == "0" ]]; then
  exit 0
fi

# locked: ignore launching `linux.sh'
if [[ -f /tmp/xsession.lock ]]; then
  exit 0
else
  touch /tmp/xsession.lock

  export XINITSLEEP=/home/mh/Scripts/system/linux.sh
  export XINITSLEEPARGS=-x
  $TERM -e zsh
fi
