#!/usr/bin/sh

# TODO: we could get the client terminal from here, though it'd only work with
# non-pipes

case $1 in
  '--help'|'-h')
    echo "Usage:       tmuxc COMMAND"
    echo "Description: Send output of COMMAND on the client TTY of tmux"
    exit 0;;
  *)
    cmd=$@;;
esac

term=""
CT=$(tmux display-message -p "#{client_tty}" 2>/dev/null)
export TTY="$CT"

if [[ "$CT" == "\n" || -z "$CT" ]]; then
  exit 0
else
  term="> $CT"
fi

[[ -z $cmd ]] && cmd="cat"

eval $cmd $term
