#!/usr/bin/sh

case $1 in
  '--help'|'-h')
    echo "Usage:       tmuxa [OPTIONS] SESSION"
    echo "Description: Attach a tmux SESSION given environment"
    echo "Options:
  -x: run it in X"
    exit 1;;
esac

XTERM=urxvt

CT=$(tmux display-message -p "#{client_tty}" 2>/dev/null)

if [[ $1 == '-x' ]]; then
  SESSION=$2
  TMUX_ATTACH="($XTERM -e tmux attach-session -t '$SESSION' &)"
else
  SESSION=$1
  TMUX_ATTACH="tmux attach-session -t '$SESSION'"
fi

if [[ ! -z $SESSION ]]; then
  SESSION="-t $SESSION"
fi

if [[ "$CT" == "\n" ]]; then
  exit 0
elif [[ -z "$CT" ]]; then
  eval "$TMUX_ATTACH"
else
  exec tmux switch-client -c $CT $SESSION
fi
