#!/usr/bin/sh

case $1 in
  '--help'|'-h')
    echo "Usage:       tmux-comp TYPE OUTPUT"
    echo "Description: Run a FZF completion on tmux's pane contents given the \
TYPE"
    echo "Types:
  -w: word
  -s: symbol
  -l: line"
    echo "Output:
  -i: output inline (default)
  -s: save to buffer"
    exit 0;;
  '-w') re='\w+' ;;
  '-s') re='[A-Za-z0-9\-_/~]+' ;;
  '-l') re='^.+$' ;;
  *)
    echo "[ !! ] Wrong type. See \`--help'"
    exit 1;;
esac

case $2 in
  '-i') output="tmux paste-buffer -p" ;;
  '-s') output="true";;
esac

line=$(tmux capturep -p -S- -E- |\
       grep -Eo "$re" | sort | uniq | fzf)

[[ ! -z "$line" ]] && echo -n "$line" | tmux loadb - && eval $output

tmux display-popup -C
