#!/usr/bin/sh

case $1 in
  '-h'|'--help')
    echo "Usage:       tmux-bg"
    echo "Description: Apply background for urxvt as the tmux client"
    exit 0
    ;;
esac

CT=$(tmux display-message -p "#{client_tty}")

if [[ -z "$CT" || "$CT" == "\n" ]]; then
  exit 0
fi

# force my tmux to set the BG variable to the current background
printf '\033]11;?\033\\' > $CT

# set BG as used
tmux setenv -gh _BG 1

# get the variable, and set the style
bg=$(tmux showenv -gh BG 2>/dev/null | cut -d= -f2)
[[ -z $bg ]] && exit 0

style="bg=#$bg"

tmux set -g window-style "$style" >&/dev/null
tmux set -swp window-style "$style" >&/dev/null
