#!/usr/bin/sh

AS=${0##*/}

EMACSCLIENT=emacsclient
EMACSALT=emacs

case $1 in
  '--help'|'-h')
  echo "Usage:       emacsc [emacs options]"
  echo "Description: Connects to an emacs client"
  exit 1
esac

exec $EMACSCLIENT -t -s "/tmp/emacs/server" ${@:1} -a "$EMACSALT"
